# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /images/default_post_bg.jpg
page_menu_button: dark
post_menu_button: light
title_plancehold: 随笔
author:
  head: images/profile.jpg
  signature: Thoughts about pixels, voxels and texels.
navication:
  - name: Github
    link: https://github.com/jonathanlurie
  - name: Twitter
    link: https://twitter.com/jonathanlurie
  - name: About
    link: http://me.jonathanlurie.fr
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/jonathanlurie
  - name: Twitter
    icon: twitter
    link: https://twitter.com/jonathanlurie
# Duoshuo
duoshuo:
  enable: false
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: false
  laughing: false
